### PR TITLE
made it compile under linux

### PR DESCRIPTION
**Pull request by ghost**
see commit notes. added cmake config for linux / g++4.9. cmake should also work for windows with the correct compiler. 
integrated libcryptopp as submodule to pull the current version from github. usage:
$ git submodule init
$ git submodule update
$ cmake .
$ make

doMakeLinux.sh script added as workaround for wrong libcryptopp install path, needs fix

added guards and typedefs to make it compile for linux. needs global strategy for platform dependent stuff

### CODE REVIEW

**Comment by mrc-g** [comment]
Seems you have done a great job!
On Wednesday I'll test and merge if everything is ok.
I really appreciate your help!

**Comment by ghost** [comment]
hi! possibly you'll get an update up to then, there are still some small things to do... best regards, gerhard

**Comment by mrc-g** [comment]
It tell me that ../libcryptopp.git does not exist, I changed CMakeLists.txt  the path in /libcryptopp/.git and it compiled but still can't link because it gave me "undefine reference to `CryptoPP::Integer::Integer..."

**Comment by mrc-g** [comment]
I made it! Changed CMakeLists.txt in BitMRC to point to an actual lib and to use it in target_link_libraries

**Comment by ghost** [comment]
tried to move headers to include/ .. but there is something wrong. so i reverted.
types.h now holds macros for renaming windows specific functions. so we do not need to add that lot of guards...

**Comment by ghost** [comment]
Marco, do you have a BitMessage Address ?

**Comment by ghost** [comment]
endian.h needs to be fixed for windows now, since i moved it.

**Comment by ghost** [comment]
missing file added : EndianTest.cpp

**Comment by mrc-g** [comment]
Yes
BM-2cUkq9ECTthvXspWVftYQd3xWrrNQnzzjt

**Pull request merged**
