### PR TITLE
Fix some warnings and move trials to one directory

### PR DESCRIPTION
**Pull request by ghost**
trials may be enabled by cmake . -DENABLE_TRIALS=1

### CODE REVIEW

**Comment by ghost** [comment]
Marco,
heres a little bug:

Select a command (help): address generate deterministic
Passphrase: 123
terminate called after throwing an instance of 'std::runtime_error'
  what():  cannot encode base58

The same happens here if using random generation

**Comment by mrc-g** [comment]
It also happened to me but, I was never able to reproduce the bug so I ignored it.
I'm going to investigate because I'm still unable to reproduce even with your passphrase.
It only happened once on Linux.

**Comment by mrc-g** [comment]
I fixed the problem! check it.

**Comment by ghost** [comment]
works ! awesome ... ;-)

**Pull request merged**
